# Generated by Django 5.0.6 on 2024-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog_data',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog_data',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
