# Generated by Django 5.0.6 on 2024-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_data_author_alter_blog_data_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='image',
            field=models.ImageField(blank=True, default='home/assets/placeholder.png', null=True, upload_to=''),
        ),
    ]
