# Generated by Django 5.0.6 on 2024-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to=''),
        ),
    ]
